# Dependencies
markdown: kramdown
highlighter: rouge

# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Settings
color: '#fab005'
exclude:
  [
    CNAME,
    README.md,
    NOTES.md,
    LICENSE.md,
    .gitignore,
    package.json,
    _js,
    _scss,
    _images,
    gulpfile.js,
    gulpconfig.js,
    node_modules,
    gemfile,
    Gemfile.lock,
  ]
permalink: /:title/
compress_html:
  clippings: all
  comments: all
dark_theme: false

# Site meta
title: Kontentchi Space
tagline: 'Эне тилде подкаст'
description: 'Подкастчы авторлорду бириктирген платформа.'
keywords: 'kontentchi, контентчи, кыргызча, подкаст, kyrgyz, podcast, kyrgyzstan, people'
url: https://kontentchispace.github.io
baseurl: https://kontentchispace.github.io/
assets: /assets
images: /images/
image: index-large.jpg
logo: /assets/icons/apple-icon-144x144.png

author:
  name: Kontnetchi Space
  bio: Кандай! Бул Контентчи Space, подкастчы авторлорду бириктирген платформа. Баштан!
  image: author
  url: https://kontentchi.com
  email: kontentchiplatform@gmail.com
  twitter: kontentchi

social:
  twitter: https://twitter.com/kontentchi
  instagram: https://instagram.com/kontentchi
  github: https://github.com/kontentchispace

version: 2.0.0

github:
  repo: https://github.com/connor-baer/summer

# Integrations
# typekit:              fcv7rfe

google_fonts:
  Overpass: 400, 600, 800

# google_analytics_key: UA-37412525-4
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

# Content
excerpt_separator: <!-- Read more -->

navigation:
  Инфо: https://kontentchispace.github.io/pages/info.html

collections:
  recipes:
    output: true

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      lang: en
      permalink: /news/:title/
  - scope:
      path: ''
      type: recipes
    values:
      layout: recipe
      lang: en
      permalink: /:title/
